### ISSUE TITLE
SWARM Mini-summit

### ISSUE THREAD

**Issue by pet3r-pan** [JosefJ/PragueBlockchainWeek#10]
If you're submitting an event, please read the instructions below and fill in
the content. Otherwise just remove all the content of this issue and explain
in detail the problem you're experiencing.

---
####################
####################
# This file is a template to create new events.
# _Don't_ remove any text before the colons at the beginning of each line,
# only edit what is after the colon. Example:
# Don't remove the word nor colon on 'description:'
#
# Every line starting with a hash symbol (#) is a comment. It will be ignored
# and can be safely removed, including these instructions.
###############

###########
###########
# The title of the page, displayed by the browser on the title of the window.
# Ideally this is the same as the name of the event.
title: SWARM Mini-summit

# Description for this event. This will be rendered as a <meta> tag in the HTML,
# and displayed on the /events page. Keep it short.
# Linebreaks are ignored, but they _must_ start with two spaces.
description: A open public day-long mini summit on SWARM with 12 talks and a hands-on workshop.

#####################
#####################
# The name of the event you're creating.
# Ideally this is the same as the title.
name: SWARM Mini-summit

# There _needs_ to be one hyphen before each paragraph.
# Linebreaks are ignored, but they _must_ start with two spaces.
# Indentation is crucial:
# Two spaces before the hyphen, four spaces before the text. _No_ tabs allowed.
# Add or remove paragraphs as needed, but remember the hyphen before each entry.
synopsis:
  -
    As Prague Blockchain week quickly approaches and new workshops, meetups, and hackathons pop up each day, it is evident that the community has drastically grown since Devcon3 in Cancun just a year ago. Proof that Devcon, the annual Ethereum conference, brings together people from all disciplines and backgrounds who share a common belief in the decentralised web we are collectively building. A key figure in the push for this decentralized vision is the team behind the distributed storage platform and content distribution network – SWARM.  
  -
    We are pleased to open up the Status Hackathon #CryptoLife venue, National House Smichov, to the SWARM team to host a mini-summit that will take place on Monday, the 29th of October. The day-long mini summit accommodates 12 talks and a hands-on workshop and is open to the public.
-
    The Swarm mini-summit will be held in conjunction with EthMagicians’ Council of Prague event. While these two events are entirely separate with different focus, it will be of our great pleasure to host these bright minds under the same roof in joint efforts to work together on the challenges that hinder widespread web3 adoption. Both the SWARM team and EthMagicians will have dedicated spaces within the National House Smichov.
 
# The date should be in the format year-month-day (ISO 8601).
# Example: 2018-02-28
date: 2018-10-26
# The date when the event ends. Can be left empty or set to the same day the
# event starts.
endDate: 2018-10-26

# Set the time in 24 hours format, surrounded by quotes.
# _Only_ the starting time!
# Example: '18:00'
time: '09:00'
# Time when the event ends. Can be left empty.
endTime: '17:00'

# The URL where to akquire the tickets. Can be left empty.
tickets: https://www.eventbrite.com/e/swarm-mini-summit-prague-tickets-50685451550

# If the entrance is free, set zero (0) as the price, or leave it empty.
# _Don't_ write the currency symbol (EUR symbol will be used).
price: 0

# The name of the venue where the event will be held. Can be left empty.
venue: FULL NODE

# The address to link to a Google map. Please test the address on Google Maps.
# Example: 5. května 1640/65, 140 21 Praha 4
address: National House Smíchov, náměstí 14.října 16, 150 00 Praha 

# The category of the event. Valid options:
# - conference
# - event
# - hackathon
# - workshop
# - party
# Use _only_ one, and don't capitalize.
category: conference

#################
#################
# There _needs_ to be one hyphen before each entry.
# Linebreaks are ignored, but they _must_ start with two spaces.
# Indentation is crucial:
# Two spaces before the hyphen, four spaces before the text. _No_ tabs allowed.
# Add or remove speakers as needed, but remember the hyphen before each entry.
speakers:
  -
    # Required.
    name: -

    # Can be left empty.
    title: -

    # Can be left empty.
    company: -

    # The full URL, including http(s)://. Can be left empty.
    companyURL: -

    # Just the twitter handle, without Twitter's URL, nor the '@' symbol.
    # Can be left empty.
    twitter: -

    # The full URL, including http(s)://. Can be left empty.
    website: -

    # The bio is a single line.
    # Linebreaks are ignored, but they _must_ start with two spaces.
    bio: -
  -
    name: -
    title: -
    company: -
    companyURL: -
    twitter: -
    website: -
    bio: -
  -
    name: -
    title: -
    company: -
    companyURL: -
    twitter: -
    website: -
    bio: -

### DON'T MAKE CHANGES BELOW THIS LINE! ###
---

<Event-Content/>

**Comment by JosefJ** [comment]
Thanks a lot for filling out the template! 
https://github.com/JosefJ/PragueBlockchainWeek/commit/a680e7d5cb26fb4f0ec30451d5a152186ff12d96
