### ISSUE TITLE
Add Algorand Blockchain Meetup Prague

### ISSUE THREAD

**Issue by sjors-lemniscap** [JosefJ/PragueBlockchainWeek#11]
If you're submitting an event, please read the instructions below and fill in
the content. Otherwise just remove all the content of this issue and explain
in detail the problem you're experiencing.

---
####################
####################
# This file is a template to create new events.
# _Don't_ remove any text before the colons at the beginning of each line,
# only edit what is after the colon. Example:
# Don't remove the word nor colon on 'description:'
#
# Every line starting with a hash symbol (#) is a comment. It will be ignored
# and can be safely removed, including these instructions.
###############

###########
###########
# The title of the page, displayed by the browser on the title of the window.
# Ideally this is the same as the name of the event.
title: Algorand Prague Blockchain Meetup

# Description for this event. This will be rendered as a <meta> tag in the HTML,
# and displayed on the /events page. Keep it short.
# Linebreaks are ignored, but they _must_ start with two spaces.
description: We invite the Prague blockchain developers community to join us for an evening of networking, drinks and meeting the Algorand team.

#####################
#####################
# The name of the event you're creating.
# Ideally this is the same as the title.
name: Algorand Prague Blockchain Meetup

# There _needs_ to be one hyphen before each paragraph.
# Linebreaks are ignored, but they _must_ start with two spaces.
# Indentation is crucial:
# Two spaces before the hyphen, four spaces before the text. _No_ tabs allowed.
# Add or remove paragraphs as needed, but remember the hyphen before each entry.
synopsis:
  -
    We invite the Prague blockchain developers community to join us for an evening of networking, drinks and meeting the Algorand team to hear about the revolutionary alternative blockchain, developed from the first principles and enabling continuous progress. 
  -
    Turing Award winner and an MIT professor Silvio Micali will tell you about how Algorand is changing the conversation in the blockchain space.
  -
    Agenda:
    * 18:30 - 19:30 Walk-in & Networking
    * 19:30 - 20:15 Algorand Project Presentation + Q&A by Silvio Micali
    * 20:15 - 20:30 Algorand Developer Suite of Tools by Şahver Kaya
    * 20:30 - 22:00 Networking

# The date should be in the format year-month-day (ISO 8601).
# Example: 2018-02-28
date: 2018-11-02
# The date when the event ends. Can be left empty or set to the same day the
# event starts.
endDate: 2018-11-02

# Set the time in 24 hours format, surrounded by quotes.
# _Only_ the starting time!
# Example: '18:30'
time: '18:30'
# Time when the event ends. Can be left empty.
endTime: '22:00'

# The URL where to akquire the tickets. Can be left empty.
tickets: https://www.eventbrite.com/e/algorand-blockchain-meetup-prague-tickets-50969326628

# If the entrance is free, set zero (0) as the price, or leave it empty.
# _Don't_ write the currency symbol (EUR symbol will be used).
price: 0

# The name of the venue where the event will be held. Can be left empty.
venue: Paralelní Polis

# The address to link to a Google map. Please test the address on Google Maps.
# Example: 5. května 1640/65, 140 21 Praha 4
address: Dělnická 475/43, 170 00 Praha 7, Czechia

# The category of the event. Valid options:
# - conference
# - event
# - hackathon
# - workshop
# - party
# Use _only_ one, and don't capitalize.
category: event

#################
#################
# There _needs_ to be one hyphen before each entry.
# Linebreaks are ignored, but they _must_ start with two spaces.
# Indentation is crucial:
# Two spaces before the hyphen, four spaces before the text. _No_ tabs allowed.
# Add or remove speakers as needed, but remember the hyphen before each entry.
speakers:
  -
    # Required.
    name: Silvio Micali

    # Can be left empty.
    title: Founder

    # Can be left empty.
    company: Algorand

    # The full URL, including http(s)://. Can be left empty.
    companyURL: https://algorand.com

    # Just the twitter handle, without Twitter's URL, nor the '@' symbol.
    # Can be left empty.
    twitter: Algorand

    # The full URL, including http(s)://. Can be left empty.
    website: 

    # The bio is a single line.
    # Linebreaks are ignored, but they _must_ start with two spaces.
    bio: Silvio Micali is the Founder of Algorand, a revolutionary new blockchain that solves the "Blockchain Trilemma" by being truly scalable, secure and decentralized. 
  -
    name: Şahver Kaya
    title: Head of EMEA
    company: Algorand
    companyURL: https://algorand.com
    twitter: sbinici_
    bio: Şahver Kaya is an international executive with extensive experience in USA, Europe and Asia.

### DON'T MAKE CHANGES BELOW THIS LINE! ###
---

<Event-Content/>

**Comment by JosefJ** [comment]
Thanks! Listed: https://github.com/JosefJ/PragueBlockchainWeek/commit/3cf21634d96d3f2b042e119158a95bd5fe804af0

**Comment by sjors-lemniscap** [comment]
@JosefJ Agenda formatting seems to be messed up. I've made a couple of other changes as well:

- Event time changed from 18:00 to 18:30

- Can we make the Agenda similar as here (with the bullet points): https://blockchainweek.berlin/events/lemniscap-presents-berlin-blockchain-week-meetup/

- Changed the Agenda description

- Changed the second paragraph of the event description

- Corrected Twitter profile of Şahver Kaya 

- Can we add this URL for the address: https://goo.gl/maps/vVqftACf32A2 Current Google Maps URL doesn't work.

- Can we add a last paragraph "Event partner: Lemniscap" where we can hyperlink "Lemniscap" to https://lemniscap.com ? (I didn't add this in the changed issue).

Thanks a lot!

**Comment by JosefJ** [comment]
See: https://github.com/JosefJ/PragueBlockchainWeek/commit/9e002ad4a2a951eb258df8858f88bb6cf81f5109

**Comment by JosefJ** [comment]
See: 9e002ad

**Comment by sjors-lemniscap** [comment]
@JosefJ That was fast. Thanks! Still a couple of things:

- Change Twitter handle from Sahver to: sbinici_

- Remove the "-" after the paragraphs

- Add speakers to the Agenda description (see initial Issue)

Thanks again!

**Comment by sjors-lemniscap** [comment]
@JosefJ Please see my previous comment. Let me know if there are any difficulties and thanks again for fixing this.

**Comment by JosefJ** [comment]
FYI: I'm not tracking closed issues. If you have any request, feel free to reopen the issue.

**Comment by JosefJ** [comment]
https://pragueblockchainweek.cz/events/algorand/
https://github.com/JosefJ/PragueBlockchainWeek/commit/e42b0c6df2e0385193581a7dab46aaaf1ea2e212
https://github.com/JosefJ/PragueBlockchainWeek/commit/1d989684860f0d4857e712c851bab65347b3daba

Should be all good, please clear your browser cache in case you are not seeing the changes.
