### ISSUE TITLE
Amenities Request

### ISSUE THREAD

**Issue by waynesworldza** [JosefJ/PragueBlockchainWeek#14]
https://www.eventbrite.com/e/devcon4-ethereum-organizer-meetup-tickets-49469283960

Hi Josef! You assisted me with the booking at this venue and I was hoping you could help me again. We're looking to inquire if the restaurant would be able to give us a private-ish space with access to amenities like a screen/TV/Monitor for us to use?

Regards
Wayne

**Comment by JosefJ** [comment]
Hi, did you asked them via an email already?

**Comment by waynesworldza** [comment]
No I haven't, I assumed there might be a language barrier but I'll give it a go.

**Comment by waynesworldza** [comment]
Hi josef, booking sorted, We've had to change the time of the event to 18h30-20h30 though, which means I'll need assistance in changing this on the PragueBlockchainCalendar

**Comment by JosefJ** [comment]
https://github.com/JosefJ/PragueBlockchainWeek/commit/9a584f44e40ba052515bd0004b21b31afd978cc4
