### ISSUE TITLE
Aragon Dream DAO Party

### ISSUE THREAD

**Issue by john-light** [JosefJ/PragueBlockchainWeek#15]
If you're submitting an event, please read the instructions below and fill in
the content. Otherwise just remove all the content of this issue and explain
in detail the problem you're experiencing.

---
####################
####################
# This file is a template to create new events.
# _Don't_ remove any text before the colons at the beginning of each line,
# only edit what is after the colon. Example:
# Don't remove the word nor colon on 'description:'
#
# Every line starting with a hash symbol (#) is a comment. It will be ignored
# and can be safely removed, including these instructions.
###############

###########
###########
# The title of the page, displayed by the browser on the title of the window.
# Ideally this is the same as the name of the event.
title: Aragon Dream DAO Party

# Description for this event. This will be rendered as a <meta> tag in the HTML,
# and displayed on the /events page. Keep it short.
# Linebreaks are ignored, but they _must_ start with two spaces.
description: The Aragon team invites you to join us in Prague on November 1st for an evening of entertainment and community.

#####################
#####################
# The name of the event you're creating.
# Ideally this is the same as the title.
name: Aragon Dream DAO Party

# There _needs_ to be one hyphen before each paragraph.
# Linebreaks are ignored, but they _must_ start with two spaces.
# Indentation is crucial:
# Two spaces before the hyphen, four spaces before the text. _No_ tabs allowed.
# Add or remove paragraphs as needed, but remember the hyphen before each entry.
synopsis:
  -
    The Aragon team invites you to join us in Prague on November 1st for an evening of entertainment and community.
  -
    Do you dream about using Decentralized Autonomous Organizations to improve your community? We are offering a chance to help make your dreams come true!
  -
    After socializing over food and drinks, we will be hosting the first Dream DAO pitch contest. Attendees will be able to sign up to give a five minute pitch of their Dream DAO for a chance to win a grand prize of 500 ANT and 500 DAI, with a runner up prize of 250 ANT and 250 DAI. 
  -
    Pitches will be judged by a panel of Aragon community members based on the potential positive impact of the DAO and the realistic likelihood that the DAO will succeed when it is launched. Bonus points will be given for creativity and ambition!
  -
    After the pitch contest, we will continue partying into the night, chilling and dancing to beats mixed by talented DJs from the Ethereum community.
  -
    **Schedule**
  -
    18:30 - Doors open + food is served
    19:00 - Dream DAO pitch contest begins
    20:30 - Pitch contest winner announced
    20:35 - Partying continues
    Midnight - Party ends!
  -
    **Pitch contest details**
  -
    Grand Prize: 500 ANT + 500 DAI + enough ETH to deploy the Dream DAO.
  -
    Runner-up Prize: 250 ANT + 250 DAI + enough ETH to deploy the Dream DAO.
  -
    Pitch length: 5 minutes, no slides, all passion.
  -
    Sign-up in person at the event, first come first served. 15 contestants max.

# The date should be in the format year-month-day (ISO 8601).
# Example: 2018-02-28
date: 2018-11-01
# The date when the event ends. Can be left empty or set to the same day the
# event starts.
endDate:

# Set the time in 24 hours format, surrounded by quotes.
# _Only_ the starting time!
# Example: '18:00'
time: '18:30'
# Time when the event ends. Can be left empty.
endTime:

# The URL where to akquire the tickets. Can be left empty.
tickets: https://kickback.events/event/0xecbc1cf6e45aada03cf557cfd20f85be9b29327d

# If the entrance is free, set zero (0) as the price, or leave it empty.
# _Don't_ write the currency symbol (EUR symbol will be used).
price:

# The name of the venue where the event will be held. Can be left empty.
venue: Rockberry Bar & Music Club

# The address to link to a Google map. Please test the address on Google Maps.
# Example: 5. května 1640/65, 140 21 Praha 4
address: Sekaninova 56, 128 00, Praha 2

# The category of the event. Valid options:
# - conference
# - event
# - hackathon
# - workshop
# - party
# Use _only_ one, and don't capitalize.
category: party

### DON'T MAKE CHANGES BELOW THIS LINE! ###
---

<Event-Content/>

**Comment by JosefJ** [comment]
Thanks! For future updates, please edit the content and reopen the issue :) 
https://github.com/JosefJ/PragueBlockchainWeek/commit/a374f80a8103698e73acbf1061b90e2e22fca1ac

**Comment by john-light** [comment]
Just updated the entry. I cannot reopen the issue, please re-open @JosefJ  :)

**Comment by JosefJ** [comment]
Changed: https://github.com/JosefJ/PragueBlockchainWeek/commit/514c8d1b3d3204ba475cf41e08059afaab26a1ad

Check it here and if it's ok, please close the issue:
https://pragueblockchainweek.cz/events/aragon-party/
