### ISSUE TITLE
Change / Edit Algorand Blockchain Meetup Prague

### ISSUE THREAD

**Issue by sjors-lemniscap** [JosefJ/PragueBlockchainWeek#19]
Could the following be added to the "[Algorand Prague Blockchain Meetup page](https://pragueblockchainweek.cz/events/algorand/)":

**Agenda changes:**
Can we make the "Agenda:" text bold? (Just the title / heading).
- 18:30 - 19:30 Walk-in & Networking
- 19:30 - 20:15 Algorand Project Presentation + Q&A by Silvio Micali
- 20:15 - 20:45 Algorand Developer Tools by Naveed Ihsanullah
- 20:45 - 21:00 Algorand Ecosystem, Community and Partnerships by Şahver Kaya
- 20:30 - 22:00 Networking

**Speaker changes:**
Add the following speaker:
- Name: Naveed Ihsanullah
- Title: Head of Engineering
- Bio: Naveed Ihsanullah is a senior engineering leader and technologist fascinated by distributed systems and performance. 
- Website: https://algorand.com
- Company: Algorand
- Twitter: https://twitter.com/naveedi

Please make sure the speakers order is as follows: 1. Silvio, 2. Naveed, 3. Şahver

Everything else can remain the same. Thanks a lot!

**Comment by JosefJ** [comment]
changed the content, can't change styling: https://github.com/JosefJ/PragueBlockchainWeek/commit/9ca3bcac2c98881165de2f08b892837585739092

Please close the issue if it's alright ;)

**Comment by JosefJ** [comment]
good now?

**Comment by sjors-lemniscap** [comment]
@JosefJ Still some issues (sorry):

- Can we change the "website" tag to the "companyURL" tag for Naveed

- Naveed's twitter URL seems to be broken. There's an "@" in front of the URL. The Twitter handle is "naveedi"

- Can we add the following inbetween the "agenda" and "Event partner: lemniscap": Transportation options from Devcon4 venue to Paralelní Polis: [Google Maps](https://www.google.com/maps/dir/Prague+Congress+Centre,+5.+kv%C4%9Btna+1640%2F65,+140+21+Praha+4,+Czechia/Paraleln%C3%AD+Polis,+D%C4%9Blnick%C3%A1+475%2F43,+170+00+Praha+7,+Czechia/@50.0818121,14.4163387,14z/data=!4m14!4m13!1m5!1m1!1s0x470b9464c186eb79:0x4d26855708eb61f7!2m2!1d14.428506!2d50.062033!1m5!1m1!1s0x470b94b186427997:0xcad994427e27c9c0!2m2!1d14.4505577!2d50.1033854!3e0)

**Comment by JosefJ** [comment]
changed: https://pragueblockchainweek.cz/events/algorand/
Please close the issue ;)

**Comment by sjors-lemniscap** [comment]
@JosefJ Please change for all speakers the "website: https://algorand.com" for "companyURL: https://algorand.com". This is the last issue that needs to be fixed. Thanks a lot.

**Comment by JosefJ** [comment]
Done: https://github.com/JosefJ/PragueBlockchainWeek/commit/c6461ce41ba852df841d7917113aa69b82ef283a

**Comment by JosefJ** [comment]
Service is down atm: https://stackoverflow.com/questions/52925779/git-pages-are-not-updating

**Comment by sjors-lemniscap** [comment]
Thanks @JosefJ - Seems to be a pretty serious outage. Meanwhile can we add one more change?

- Change the event end time to 01:00 AM (next day / night)

- Add the following on the last line in the agenda: "22:00 - 01:00 Drinks at [Avion 58](https://goo.gl/maps/dnBE3Ek975H2) bar (4min walk from Paralelní Polis)"

Thanks! All other changes look good.

**Comment by JosefJ** [comment]
should be done
