### ISSUE TITLE
#CryptoLife with Status

### ISSUE THREAD

**Issue by andytudhope** [JosefJ/PragueBlockchainWeek#2]
If you're submitting an event, please read the instructions below and fill in
the content. Otherwise just remove all the content of this issue and explain
in detail the problem you're experiencing.

---
####################
####################
# This file is a template to create new events.
# _Don't_ remove any text before the colons at the beginning of each line,
# only edit what is after the colon. Example:
# Don't remove the word nor colon on 'description:'
#
# Every line starting with a hash symbol (#) is a comment. It will be ignored
# and can be safely removed, including these instructions.
###############

###########
###########
# The title of the page, displayed by the browser on the title of the window.
# Ideally this is the same as the name of the event.
title: #CryptoLife

# Description for this event. This will be rendered as a <meta> tag in the HTML,
# and displayed on the /events page. Keep it short.
# Linebreaks are ignored, but they _must_ start with two spaces.
description: 

#####################
#####################
# The name of the event you're creating.
# Ideally this is the same as the title.
name: #CryptoLife

# There _needs_ to be one hyphen before each paragraph.
# Linebreaks are ignored, but they _must_ start with two spaces.
# Indentation is crucial:
# Two spaces before the hyphen, four spaces before the text. _No_ tabs allowed.
# Add or remove paragraphs as needed, but remember the hyphen before each entry.
synopsis: In order to advance the mass adoption of Ethereum, we need to build truly distributed applications that people can use easily on a day-to-day basis and from which they can genuinely benefit. Join us in Prague to #buidl the tools, products, and services which will bring crypto closer to life. From Travel, to Marketplaces, EIPs and Interoperability, Games, and Social tools; the best minds are gathering the weekend before DevCon to pull the future closer to reality. Join us and #buidl on the bleeding edge of the possible.

# The date should be in the format year-month-day (ISO 8601).
# Example: 2018-02-28
date: 2018-10-26
# The date when the event ends. Can be left empty or set to the same day the
# event starts.
endDate: 2018-10-28

# Set the time in 24 hours format, surrounded by quotes.
# _Only_ the starting time!
# Example: '18:00'
time: '09:00'
# Time when the event ends. Can be left empty.
endTime: '00:00'

# The URL where to akquire the tickets. Can be left empty.
tickets: https://hackathon.status.im
# If the entrance is free, set zero (0) as the price, or leave it empty.
# _Don't_ write the currency symbol (Kč symbol will be used).
price: 0

# The name of the venue where the event will be held. Can be left empty.
venue: The National House Smichov

# The address to link to a Google map. Please test the address on Google Maps.
# Example: 5. května 1640/65, 140 21 Praha 4
address: [náměstí 14. října, Prague-Smíchov](https://www.google.co.za/maps/place/National+House+Sm%C3%ADchov/@50.0738213,14.4054537,17z/data=!3m1!4b1!4m5!3m4!1s0x470b94f824acf147:0xff9900e4add1873!8m2!3d50.0738179!4d14.4076477)

# The category of the event. Valid options:
# - conference
# - event
# - hackathon
# - workshop
# - party
# Use _only_ one, and don't capitalize.
category: hackathon

#################
#################
# There _needs_ to be one hyphen before each entry.
# Linebreaks are ignored, but they _must_ start with two spaces.
# Indentation is crucial:
# Two spaces before the hyphen, four spaces before the text. _No_ tabs allowed.
# Add or remove speakers as needed, but remember the hyphen before each entry.
speakers:
  -
    # Required.
    name: Andy Tudhope

    # Can be left empty.
    title: Developer Relations

    # Can be left empty.
    company: Status

    # The full URL, including http(s)://. Can be left empty.
    companyURL: https://status.im

    # Just the twitter handle, without Twitter's URL, nor the '@' symbol.
    # Can be left empty.
    twitter: cryptowanderer

    # The full URL, including http(s)://. Can be left empty.
    website: https://hackathon.status.im

    # The bio is a single line.
    # Linebreaks are ignored, but they _must_ start with two spaces.
    bio: With a background in both Applied Mathematics and English Literature, Andy is interested in the intersection of common programming languages for reaching consensus and the implementation of a global, shared substrate for computation. He came to work on Ethereum - and with Status in particular - in order to further his research into the idea of a perfect language. 

### DON'T MAKE CHANGES BELOW THIS LINE! ###
---

<Event-Content/>

**Comment by JosefJ** [comment]
https://github.com/JosefJ/PragueBlockchainWeek/commit/38d8ce03f89f57498f04261ae05333e015357848
