### ISSUE TITLE
Cryptoween: Golem, Streamr, OmiseGo and ECF

### ISSUE THREAD

**Issue by mariapaulafn** [JosefJ/PragueBlockchainWeek#22]
If you're submitting an event, please read the instructions below and fill in
the content. Otherwise just remove all the content of this issue and explain
in detail the problem you're experiencing.

---
####################
####################
# This file is a template to create new events.
# _Don't_ remove any text before the colons at the beginning of each line,
# only edit what is after the colon. Example:
# Don't remove the word nor colon on 'description:'
#
# Every line starting with a hash symbol (#) is a comment. It will be ignored
# and can be safely removed, including these instructions.
###############

###########
###########
# The title of the page, displayed by the browser on the title of the window.
# Ideally this is the same as the name of the event.
title: Cryptoween - a pre-DEVCON4 get-together by Golem, OmiseGo, Streamr & ECF

# Description for this event. This will be rendered as a <meta> tag in the HTML,
# and displayed on the /events page. Keep it short.
# Linebreaks are ignored, but they _must_ start with two spaces.
description: Come join the Golem, OmiseGo, Streamr and ECF teams for a fun and quirky Cryptoween the day before the Devcon4 kick-off! sign-up via Kickback only.  
You can expect a lovely venue, drinks, snacks and fun music - the basics to be on a really good mood in preparation for Devcon4.  

#####################
#####################
# The name of the event you're creating.
# Ideally this is the same as the title.
name: Cryptoween: Golem, Streamr, OmiseGo and ECF

# There _needs_ to be one hyphen before each paragraph.
# Linebreaks are ignored, but they _must_ start with two spaces.
# Indentation is crucial:
# Two spaces before the hyphen, four spaces before the text. _No_ tabs allowed.
# Add or remove paragraphs as needed, but remember the hyphen before each entry.
synopsis:
  -
    A pre-DEVCON4 celebration
  -
    Come join the Golem, OmiseGo, Streamr and ECF teams for a fun and quirky Cryptoween the day before the Devcon4 kick-off! sign-up via Kickback only.
  -

# The date should be in the format year-month-day (ISO 8601).
# Example: 2018-10-29
date: 2018-10-29
# The date when the event ends. Can be left empty or set to the same day the
# event starts.
endDate: 2018-10-30

# Set the time in 24 hours format, surrounded by quotes.
# _Only_ the starting time!
# Example: '18:00'
time: '21:00'
# Time when the event ends. Can be left empty.
endTime: '00:00'

# The URL where to akquire the tickets. Can be left empty.
tickets: https://kickback.events/event/0xf6912d7ab160aa1645206f6725a0f57840839799

# If the entrance is free, set zero (0) as the price, or leave it empty.
# _Don't_ write the currency symbol (EUR symbol will be used).
price: 

# The name of the venue where the event will be held. Can be left empty.
venue: Kasarna Karlin

# The address to link to a Google map. Please test the address on Google Maps.
# Example: 5. května 1640/65, 140 21 Praha 4
address: Prvního pluku 20/2, 186 00 Praha 8-Karlín

# The category of the event. Valid options:
# - conference
# - event
# - hackathon
# - workshop
# - party
# Use _only_ one, and don't capitalize.
category: party

#################
#################
# There _needs_ to be one hyphen before each entry.
# Linebreaks are ignored, but they _must_ start with two spaces.
# Indentation is crucial:
# Two spaces before the hyphen, four spaces before the text. _No_ tabs allowed.
# Add or remove speakers as needed, but remember the hyphen before each entry.
speakers:
  -

    # Just the twitter handle, without Twitter's URL, nor the '@' symbol.
    # Can be left empty.
    twitter:  @golemnetwork

    # The full URL, including http(s)://. Can be left empty.
    website: https://kickback.events/event/0xf6912d7ab160aa1645206f6725a0f57840839799

    # The bio is a single line.
    # Linebreaks are ignored, but they _must_ start with two spaces.
    bio:
  -

### DON'T MAKE CHANGES BELOW THIS LINE! ###
---

<Event-Content/>

**Comment by JosefJ** [comment]
Thanks so much for filling out the template! 
I'm sorry to find out this was apparently submitted 5 days ago already, but I'm first seeing this now :( 
(I check the issues several times a day in case I missed any notification). 

it's here: https://pragueblockchainweek.cz/events/cryptoween/

Please close the issue in case everything is ok.
