### ISSUE TITLE
Change title & time for the dai dappy hour

### ISSUE THREAD

**Issue by Lenkla** [JosefJ/PragueBlockchainWeek#23]
title
The Dai 'Dappy' Hour 
#cryptolife Prague Edition

time 
6pm- 8:30 pm

url (seems to redirect just fine, but just in case)
https://www.eventbrite.com/e/the-dai-dappy-hour-cryptolife-prague-edition-tickets-51512807193

**Comment by JosefJ** [comment]
Done - https://pragueblockchainweek.cz/events/maker-dappy-hour/
Please close the issue

**Comment by JosefJ** [comment]
The service is down: 
https://stackoverflow.com/questions/52925779/git-pages-are-not-updating
