### ISSUE TITLE
Venue Enquiry 

### ISSUE THREAD

**Issue by waynesworldza** [JosefJ/PragueBlockchainWeek#26]
Hey Josef

Due to our attendance far exceeding our expectations, we are considering changing venues to something more accommodating for 40+ people. We were thinking a brewery cellar or something private but spacious enough for everyone and cool. Do you have any ideas?

The original idea was to have the event in a casual environment like a cool brewery cellar/room to network but we are also assessing going the formal route (Presentations, Microphone + added amenities), would you know which venues would be suitable for this option too and what the cost would be out of interest?

Regards
Wayne

**Comment by JosefJ** [comment]
http://vinohradskypivovar.cz 
http://studentskyklubceletna.cz/

**Comment by waynesworldza** [comment]
Are these the only available options?

**Comment by JosefJ** [comment]
No, there is certainly more of those around.. just the first two I could think of.. 


http://www.pivolod.cz/en/home-en/
http://usudu.cz/gallery/
http://novomestsky-pivovar.czechtrade.us/

For AV I suggest you contact them directly.

**Comment by waynesworldza** [comment]
Okay cool will look at these in the meantime
