### ISSUE TITLE
Ethereum iOS DevKit hands-on workshop

### ISSUE THREAD

**Issue by JosefGattermayer** [JosefJ/PragueBlockchainWeek#3]
If you're submitting an event, please read the instructions below and fill in
the content. Otherwise just remove all the content of this issue and explain
in detail the problem you're experiencing.

---
####################
####################
# This file is a template to create new events.
# _Don't_ remove any text before the colons at the beginning of each line,
# only edit what is after the colon. Example:
# Don't remove the word nor colon on 'description:'
#
# Every line starting with a hash symbol (#) is a comment. It will be ignored
# and can be safely removed, including these instructions.
###############

###########
###########
# The title of the page, displayed by the browser on the title of the window.
# Ideally this is the same as the name of the event.
title: Ethereum iOS DevKit hands-on workshop

# Description for this event. This will be rendered as a <meta> tag in the HTML,
# and displayed on the /events page. Keep it short.
# Linebreaks are ignored, but they _must_ start with two spaces.
description: Ackee has developed iOS DevKit for Ethereum that allows native calls of smart contracts from Swift language. DevKit development has been funded by Ethereum Foundation Grant programme.

#####################
#####################
# The name of the event you're creating.
# Ideally this is the same as the title.
name: Ethereum iOS DevKit hands-on workshop

# There _needs_ to be one hyphen before each paragraph.
# Linebreaks are ignored, but they _must_ start with two spaces.
# Indentation is crucial:
# Two spaces before the hyphen, four spaces before the text. _No_ tabs allowed.
# Add or remove paragraphs as needed, but remember the hyphen before each entry.
synopsis:
  -
    This hands-on workshop will follow the official announcement of iOS DevKit at Devcon conference. 
  -
    We will shortly recap what is DevKit about (for those who didn't catch Josef's talk at Devcon) and then get into the funny part - how to use it. We will show how to build an iOS app that uses Ethereum smart contracts under 1 hour. 
  -
    Feel free to bring your own MacBooks and code with us.  

# The date should be in the format year-month-day (ISO 8601).
# Example: 2018-02-28
date: 2018-10-03
# The date when the event ends. Can be left empty or set to the same day the
# event starts.
endDate: 

# Set the time in 24 hours format, surrounded by quotes.
# _Only_ the starting time!
# Example: '18:00'
time: '17:00'
# Time when the event ends. Can be left empty.
endTime: '22:00'

# The URL where to akquire the tickets. Can be left empty.
tickets: 

# If the entrance is free, set zero (0) as the price, or leave it empty.
# _Don't_ write the currency symbol (Kč symbol will be used).
price: 0

# The name of the venue where the event will be held. Can be left empty.
venue: Ackee

# The address to link to a Google map. Please test the address on Google Maps.
# Example: 5. května 1640/65, 140 21 Praha 4
address: Karolinská 650/1, 186 00 Praha 8-Karlín 10th floor.

# The category of the event. Valid options:
# - conference
# - event
# - hackathon
# - workshop
# - party
# Use _only_ one, and don't capitalize.
category: workshop

#################
#################
# There _needs_ to be one hyphen before each entry.
# Linebreaks are ignored, but they _must_ start with two spaces.
# Indentation is crucial:
# Two spaces before the hyphen, four spaces before the text. _No_ tabs allowed.
# Add or remove speakers as needed, but remember the hyphen before each entry.
speakers:
  -
    # Required.
    name: Josef Gattermayer

    # Can be left empty.
    title: Co-founder

    # Can be left empty.
    company: Ackee

    # The full URL, including http(s)://. Can be left empty.
    companyURL: https://www.ackee.cz/en

    # Just the twitter handle, without Twitter's URL, nor the '@' symbol.
    # Can be left empty.
    twitter:

    # The full URL, including http(s)://. Can be left empty.
    website: https://www.ackee.cz/en/ethereum-ios-dev-kit

    # The bio is a single line.
    # Linebreaks are ignored, but they _must_ start with two spaces.
    bio: Josef is a co-founder of Ackee, leading Czech mobile development studio. Josef has also a doctorate (Ph.D. title) from the Czech Technical University in Prague, his area of research was distributed computing - as he calls it "blockchain before it was cool to call it blockchain". 
  -
    name: Marek Fořt
    title: iOS Developer
    company: Ackee
    companyURL: https://www.ackee.cz/en
    twitter:
    website: 
    bio: Marek is one of the iOS Ethereum DevKit team members at Ackee.

### DON'T MAKE CHANGES BELOW THIS LINE! ###
---

<Event-Content/>

**Comment by JosefJ** [comment]
https://github.com/JosefJ/PragueBlockchainWeek/commit/a1f05fe40858a06fdc9e9edb761c4eb418612f0f
