### ISSUE TITLE
Parity + Polkadot Prague Devcon Meetup 

### ISSUE THREAD

**Issue by a13xndra** [JosefJ/PragueBlockchainWeek#31]
####################
####################
# This file is a template to create new events.
# _Don't_ remove any text before the colons at the beginning of each line,
# only edit what is after the colon. Example:
# Don't remove the word nor colon on 'description:'
#
# Every line starting with a hash symbol (#) is a comment. It will be ignored
# and can be safely removed, including these instructions.
###############

###########
###########
# The title of the page, displayed by the browser on the title of the window.
# Ideally this is the same as the name of the event.
title: Parity + Polkadot Prague Devcon Meetup 

# Description for this event. This will be rendered as a <meta> tag in the HTML,
# and displayed on the /events page. Keep it short.
# Linebreaks are ignored, but they _must_ start with two spaces.
description: Special Devcon Parity & Polkadot meetup in Prague! Come relax after Devcon Day 0—food and drinks will be provided and there will be lots of time to hang out and connect.

#####################
#####################
# The name of the event you're creating.
# Ideally this is the same as the title.
name: Parity + Polkadot Prague Devcon Meetup 

# There _needs_ to be one hyphen before each paragraph.
# Linebreaks are ignored, but they _must_ start with two spaces.
# Indentation is crucial:
# Two spaces before the hyphen, four spaces before the text. _No_ tabs allowed.
# Add or remove paragraphs as needed, but remember the hyphen before each entry.
synopsis:
  -
    Special Devcon Parity & Polkadot meetup in Prague! Come relax after Devcon Day 0—food and drinks will be provided and there will be lots of time to hang out and connect.
  -
    Topics covered: 
  - 
    * build light client dapps with light.js [https://github.com/paritytech/js-libs/tree/master/packages/light.js](https://github.com/paritytech/js-libs/tree/master/packages/light.js)
  -
    * build your own blockchain with Substrate [https://parity.io/substrate](https://parity.io/substrate)
 -
    * transfer data across chains with Polkadot [https://github.com/w3f/Web3-wiki/wiki/Polkadot](https://github.com/w3f/Web3-wiki/wiki/Polkadot)

# The date should be in the format year-month-day (ISO 8601).
# Example: 2018-02-28
date: 2018-10-30
# The date when the event ends. Can be left empty or set to the same day the
# event starts.
endDate: 2018-10-30

# Set the time in 24 hours format, surrounded by quotes.
# _Only_ the starting time!
# Example: '19:00'
time: '19:30'
# Time when the event ends. Can be left empty.
endTime: '22:30'

# The URL where to akquire the tickets. Can be left empty.
tickets: https://www.meetup.com/parity/events/255665736/

# If the entrance is free, set zero (0) as the price, or leave it empty.
# _Don't_ write the currency symbol (EUR symbol will be used).
price: 0

# The name of the venue where the event will be held. Can be left empty.
venue: TBD - please check Meetup page

# The address to link to a Google map. Please test the address on Google Maps.
# Example: 5. května 1640/65, 140 21 Praha 4
address: 

# The category of the event. Valid options:
# - conference
# - event
# - hackathon
# - workshop
# - party
# Use _only_ one, and don't capitalize.
category: event

#################
#################
# There _needs_ to be one hyphen before each entry.
# Linebreaks are ignored, but they _must_ start with two spaces.
# Indentation is crucial:
# Two spaces before the hyphen, four spaces before the text. _No_ tabs allowed.
# Add or remove speakers as needed, but remember the hyphen before each entry.
speakers:
  -
    name: Jutta Steiner
    title: Founder & CEO
    company: Parity Technologies
    companyURL: https://parity.io/
    twitter: jutta_steiner
    website: 
    bio: Dr. Jutta Steiner is the CEO of Parity Technologies. Before starting Parity, she was responsible for IT security and partner integration within the Ethereum Foundation. Steiner was also a co-founder of Project Provenance Ltd, a London based start-up that employs Blockchain technology to make supply chains more transparent. She advises various projects that use Blockchain technology, such as energy start-up Grid Singularity. Steiner recently became a member of the Fortune 40 under 40.

  -
    name: Björn Wagner
    title: Founder & Chief Commercial Officer
    company: Parity Technologies
    companyURL: https://parity.io/
    twitter: bjornwgnr
    website: 
    bio: Prior to Parity, Björn gained extensive expertise in the fields of industrial automation and digitisation. Currently serving as Chief Commercial Officer, Björn is driving the company's commercialisation, partnership and product efforts. He holds a MSc. in Mechanical Engineering and Business Administration from RWTH Aachen University and studied at University of California Santa Barbara as well as Hong Kong University of Science and Technology among others.
  -
    name: Fabian Gompf
    title: VP Technology Partnerships
    company: Parity Technologies
    companyURL: https://parity.io/
    twitter: FabianGompf
    website: 
    bio: As VP of Technology Partnerships, Fabian oversees Parity Technologies' enterprise offering and is involved in the blockchain initiatives of leading organisations across industries. He is also responsible for leading the development of the UN World Health Organisation's private blockchain, which will assist 500,000 refugees by the end of 2018. Before joining Parity, Fabian was part of the early days of Electromobility in Germany through his work with StreetScooter GmbH (acquired by Deutsche Post DHL Group) and Porsche AG.
  -
    name: Amaury Martiny
    title: JavaScript Developer
    company: Parity Technologies
    companyURL: https://parity.io/
    twitter: amaurymartiny
    website: 
    bio: 
  -
    name: Anna Rose
    title: Co-Host Zero Knowledge
    company: Zero Knowledge Podcast
    companyURL: https://zeroknowledge.fm
    twitter: AnnaRRose
    website: 
    bio: 

### DON'T MAKE CHANGES BELOW THIS LINE! ###
---

<Event-Content/>

**Comment by JosefJ** [comment]
Here: https://pragueblockchainweek.cz/events/parity-polkadot/

Thanks for the submission! :) Happy to have you in town! 
Please check and close the issue
