### ISSUE TITLE
Event submission: Pandora Boxchain: Scaling high-load computing & AI in trustless environments

### ISSUE THREAD

**Issue by dany2aa** [JosefJ/PragueBlockchainWeek#38]
If you're submitting an event, please read the instructions below and fill in
the content. Otherwise just remove all the content of this issue and explain
in detail the problem you're experiencing.

---
####################
####################
# This file is a template to create new events.
# _Don't_ remove any text before the colons at the beginning of each line,
# only edit what is after the colon. Example:
# Don't remove the word nor colon on 'description:'
#
# Every line starting with a hash symbol (#) is a comment. It will be ignored
# and can be safely removed, including these instructions.
###############

###########
###########
# The title of the page, displayed by the browser on the title of the window.
# Ideally this is the same as the name of the event.
title: Pandora Boxchain: Scaling high-load computing & AI in trustless environments

# Description for this event. This will be rendered as a <meta> tag in the HTML,
# and displayed on the /events page. Keep it short.
# Linebreaks are ignored, but they _must_ start with two spaces.
description: Let's talk about The Proof of Computing Work (PoCW) protocol and the current state of technology in the field of AI and decentralization.

#####################
#####################
# The name of the event you're creating.
# Ideally this is the same as the title.
name: Pandora Boxchain: Scaling high-load computing & AI in trustless environments

# There _needs_ to be one hyphen before each paragraph.
# Linebreaks are ignored, but they _must_ start with two spaces.
# Indentation is crucial:
# Two spaces before the hyphen, four spaces before the text. _No_ tabs allowed.
# Add or remove paragraphs as needed, but remember the hyphen before each entry.
synopsis:
  -
    Pandora Boxchain is excited to announce that we are heading to Prague!
      After holding four previous meetups in Zug, Berlin, and Zurich,
      we’re now building our community in Prague and
      inviting all blockchain and AI enthusiasts to join us at ImpactHub on November 2nd,
      right after Ethereum Devcon.
  -
    Dr Maxim Orlovsky: Proof of Computing Work (PoCW).
      Why we need it and how the protocol is organized
  -
    Sergey Korostelyov: Decentralized AI. Myth or reality?
  -
    A free bar and burgers will also be on offer for attendees.
      Book your free place today before spaces fill up.
      We look forward to seeing you in Prague!

# The date should be in the format year-month-day (ISO 8601).
# Example: 2018-02-28
date: 2018-11-02
# The date when the event ends. Can be left empty or set to the same day the
# event starts.
endDate: 2018-11-02

# Set the time in 24 hours format, surrounded by quotes.
# _Only_ the starting time!
# Example: '18:00'
time: '18:30'
# Time when the event ends. Can be left empty.
endTime: '21:00'

# The URL where to akquire the tickets. Can be left empty.
tickets: https://www.meetup.com/pandoraboxchain-prague-meetup/events/255909215/

# If the entrance is free, set zero (0) as the price, or leave it empty.
# _Don't_ write the currency symbol (EUR symbol will be used).
price:

# The name of the venue where the event will be held. Can be left empty.
venue: ImpactHub Praha

# The address to link to a Google map. Please test the address on Google Maps.
# Example: 5. května 1640/65, 140 21 Praha 4
address: Drtinova 557/10, 150 00 Praha 5

# The category of the event. Valid options:
# - conference
# - event
# - hackathon
# - workshop
# - party
# Use _only_ one, and don't capitalize.
category: event

#################
#################
# There _needs_ to be one hyphen before each entry.
# Linebreaks are ignored, but they _must_ start with two spaces.
# Indentation is crucial:
# Two spaces before the hyphen, four spaces before the text. _No_ tabs allowed.
# Add or remove speakers as needed, but remember the hyphen before each entry.
speakers:
  -
    # Required.
    name: Dr Maxim Orlovsky

    # Can be left empty.
    title: Founder and Managing Director

    # Can be left empty.
    company: Pandora Boxchain

    # The full URL, including http(s)://. Can be left empty.
    companyURL: https://pandoraboxchain.ai

    # Just the twitter handle, without Twitter's URL, nor the '@' symbol.
    # Can be left empty.
    twitter: dr_orlovsky

    # The full URL, including http(s)://. Can be left empty.
    website:

    # The bio is a single line.
    # Linebreaks are ignored, but they _must_ start with two spaces.
    bio: Maxim Orlovsky is a cross-disciplinary artificial intelligence
      and neuroscience (MD, PhD) researcher,
      creator of BICA Labs (which performs research on new cognitive architectures),
      expert in complexity science, multi-agent systems, and cognitive architectures.
      Dr Orlovsky was also a co-founder of Bitcoin Foundation Ukraine in 2014 and
      holds a PhD in neuroscience and MD degrees.
  -
    name: Sergey Korostelyov
    title: Researcher and Developer, co-author of pynode computing kernels on Ethereum based PoCW consensus, blockchain and machine learning expert.
    company: Pandora Boxchain
    companyURL: https://pandoraboxchain.ai
    twitter:
    website:
    bio: Sergey has more than 10 years of experience in software architecture design and development focused on building complex enterprise systems.

### DON'T MAKE CHANGES BELOW THIS LINE! ###
---

<Event-Content/>

**Comment by JosefJ** [comment]
From format - some stuff kept from the template. Please fix/edit

**Comment by dany2aa** [comment]
@JosefJ , I've edited event submission above.
Thank you for your attention.

**Comment by JosefJ** [comment]
I've ended up editing that myself yesterday already: https://pragueblockchainweek.cz/events/Pandora/ check if it's fine :)

**Comment by dany2aa** [comment]
@JosefJ , there're a terrible error.
Please, substitute the last bio to:
Sergey has more than 10 years of experience in software architecture design and development focused on building complex enterprise systems.

I noticed the mistake when saw published event only.
I'm so sorry for my inattention.
I've corrected this text in me first post.

**Comment by dany2aa** [comment]
Also I don't see a title:
Pandora Boxchain: Scaling high-load computing & AI in trustless environments
