### ISSUE TITLE
Halloween Jam at Paralelni / 31.10.18

### ISSUE THREAD

**Issue by Matlemad** [JosefJ/PragueBlockchainWeek#4]
If you're submitting an event, please read the instructions below and fill in
the content. Otherwise just remove all the content of this issue and explain
in detail the problem you're experiencing.

---
####################
####################
# This file is a template to create new events.
# _Don't_ remove any text before the colons at the beginning of each line,
# only edit what is after the colon. Example:
# Don't remove the word nor colon on 'description:'
#
# Every line starting with a hash symbol (#) is a comment. It will be ignored
# and can be safely removed, including these instructions.
###############

###########
###########
# The title of the page, displayed by the browser on the title of the window.
# Ideally this is the same as the name of the event.
title: Halloween DEVilJam at Paralelni

# Description for this event. This will be rendered as a <meta> tag in the HTML,
# and displayed on the /events page. Keep it short.
# Linebreaks are ignored, but they _must_ start with two spaces.
description: This is a talk about blockchain. This field is indexed by search
  engines and used to show a description on /events.

Halloween Hangout and Jam Session for all musician devs at DEVCON4

#####################
#####################
# The name of the event you're creating.
# Ideally this is the same as the title.
name: Halloween DEVilJam at Paralelni

# There _needs_ to be one hyphen before each paragraph.
# Linebreaks are ignored, but they _must_ start with two spaces.
# Indentation is crucial:
# Two spaces before the hyphen, four spaces before the text. _No_ tabs allowed.
# Add or remove paragraphs as needed, but remember the hyphen before each entry.
synopsis:
  -
    There are many talented musicians among developers, and DEVCON4 will make 
     no exception. My idea is to organise a Halloween party / DEVil Jam at Paralelni, where 
     everyone can have a good time and those musicians can hack together some nice
     grooves.
  -
    I am a sound tech and musician myself and I can take of all the technical part related to the stage
    backline and sounds. I believe Paralelni Cafeteria would possibly be the best location to host it.
  -
    The whole eve can be livestreamed on Livepeer.tv using Livepeer decentralized video streaming 
    protocol.

# The date should be in the format year-month-day (ISO 8601).
# Example: 2018-02-28
date: 2018-10-31
# The date when the event ends. Can be left empty or set to the same day the
# event starts.
endDate: 2018-11-01

# Set the time in 24 hours format, surrounded by quotes.
# _Only_ the starting time!
# Example: '18:00'
time: '20:00'
# Time when the event ends. Can be left empty.
endTime: '01:00'

# The URL where to akquire the tickets. Can be left empty.
no ticket pre-sale

# If the entrance is free, set zero (0) as the price, or leave it empty.
# _Don't_ write the currency symbol (EUR symbol will be used).
price: Donation in ETH

# The name of the venue where the event will be held. Can be left empty.
venue: PARALELNI POLIS CAFETERIA

# The address to link to a Google map. Please test the address on Google Maps.
# Example: 5. května 1640/65, 140 21 Praha 4
address: Dělnická 43 Praha 7 

# The category of the event. Valid options:
# - conference
# - event
# - hackathon
# - workshop
# - party
# Use _only_ one, and don't capitalize.
category: party

### DON'T MAKE CHANGES BELOW THIS LINE! ###
---

<Event-Content/>

**Comment by JosefJ** [comment]
Hi @Matlemad, thanks for posting the issue. 
The format is broken, could you please fix it? (titles and SEO description are missing)  
Have a look at other closed issues to see which format to maintain.  
Cheers!

**Comment by Matlemad** [comment]
hey @JosefJ  is it now better? I'm sorry, I had some problems following the guidelines.

**Comment by JosefJ** [comment]
no, the title and description tags/keys are still missing

**Comment by Matlemad** [comment]
@JosefJ  ok I repasted the guidelines and followed it. I don't see any tags/keys field though.

**Comment by JosefJ** [comment]
There was the `tickets:` and `speakers:` still missing (there is an automated parser for that, that's why the form is mandatory) - changed it for you. https://github.com/JosefJ/PragueBlockchainWeek/commit/b5a93422902712b5fa61c8f4d363e680bf7c4cc5
Listed now

**Comment by Matlemad** [comment]
thank you very much @JosefJ
