### ISSUE TITLE
Ethereum Organizer Meetup

### ISSUE THREAD

**Issue by capeflow** [JosefJ/PragueBlockchainWeek#5]
If you're submitting an event, please read the instructions below and fill in
the content. Otherwise just remove all the content of this issue and explain
in detail the problem you're experiencing.

---
####################
####################
# This file is a template to create new events.
# _Don't_ remove any text before the colons at the beginning of each line,
# only edit what is after the colon. Example:
# Don't remove the word nor colon on 'description:'
#
# Every line starting with a hash symbol (#) is a comment. It will be ignored
# and can be safely removed, including these instructions.
###############

###########
###########
# The title of the page, displayed by the browser on the title of the window.
# Ideally this is the same as the name of the event.
title: Ethereum Organizer Meetup

# Description for this event. This will be rendered as a <meta> tag in the HTML,
# and displayed on the /events page. Keep it short.
# Linebreaks are ignored, but they _must_ start with two spaces.
description: Connecting Ethereum meetup organisers to share ideas
  and talk about growing the Ethereum community.

#####################
#####################
# The name of the event you're creating.
# Ideally this is the same as the title.
name: Ethereum Organizer Meetup

# There _needs_ to be one hyphen before each paragraph.
# Linebreaks are ignored, but they _must_ start with two spaces.
# Indentation is crucial:
# Two spaces before the hyphen, four spaces before the text. _No_ tabs allowed.
# Add or remove paragraphs as needed, but remember the hyphen before each entry.
synopsis:
  -
    The Protea team warmly invites all Ethereum Meetup Organisers to our 
      get together during DevCon4.
  -
    The Ethereum community is growing rapidly, already having surpassed 
      over 1 Million global meetup.com community members. Without this 
      community and those that drive it’s growth, Ethereum would not be 
      where it is today. We want to bring together all those who will be in town
      that play an active part in building the Ethereum community.
  -
    The aim of this meetup is to provide an open platform for organisers 
      to share ideas, ask questions, talk about the Ethereum community 
      and network within the industry in a fun and engaging environment. 
      Essentially, connecting Ethereum meetup organisers who are 
      attending DevCon4.
  -
    Looking forward to seeing you all there! If you have any questions, 
      don’t hesitate to get in touch.

# The date should be in the format year-month-day (ISO 8601).
# Example: 2018-02-28
date: 2018-10-31
# The date when the event ends. Can be left empty or set to the same day the
# event starts.
endDate: 2018-10-31

# Set the time in 24 hours format, surrounded by quotes.
# _Only_ the starting time!
# Example: '18:00'
time: '19:00'
# Time when the event ends. Can be left empty.
endTime: '21:00'

# The URL where to akquire the tickets. Can be left empty.
tickets: https://www.eventbrite.com/e/devcon4-ethereum-organizer-meetup-tickets-49469283960

# If the entrance is free, set zero (0) as the price, or leave it empty.
# _Don't_ write the currency symbol (EUR symbol will be used).
price: 0

# The name of the venue where the event will be held. Can be left empty.
venue: VYŠEHRADSKÝ RESTAURANT KANDELÁBR

# The address to link to a Google map. Please test the address on Google Maps.
# Example: 5. května 1640/65, 140 21 Praha 4
address: QUBIX Office Building, Štětkova 1638/18, 140 00 Praha 4, Czechia

# The category of the event. Valid options:
# - conference
# - event
# - hackathon
# - workshop
# - party
# Use _only_ one, and don't capitalize.
category: event

#################
#################
# There _needs_ to be one hyphen before each entry.
# Linebreaks are ignored, but they _must_ start with two spaces.
# Indentation is crucial:
# Two spaces before the hyphen, four spaces before the text. _No_ tabs allowed.
# Add or remove speakers as needed, but remember the hyphen before each entry.
speakers:
 
### DON'T MAKE CHANGES BELOW THIS LINE! ###
---

<Event-Content/>

**Comment by JosefJ** [comment]
https://github.com/JosefJ/PragueBlockchainWeek/commit/183b448884c2dfc9e2a5e2da31cbc1f7ec2d2276
Done, thanks!

**Comment by JosefJ** [comment]
https://github.com/JosefJ/PragueBlockchainWeek/commit/183b448884c2dfc9e2a5e2da31cbc1f7ec2d2276
Done, thanks!
