### ISSUE TITLE
Slight update of content/Edit text on Event page

### ISSUE THREAD

**Issue by blairmaclennan** [JosefJ/PragueBlockchainWeek#8]
**Request for making a small update of content**

Our event is **"iExec Summit and Party**

On the page: [https://pragueblockchainweek.cz/events/]

Would it be possible to update the text under our event to read: 

> The iExec team invite you to join us for a whole afternoon and evening of free blockchain and tech themed workshops, talks, discussions; food, drink and parties!

- I noticed it has been updated once you click on the event but we would like this to be the catchy tag line to be seen at first glance on the page of all events. 

Many thanks in advance! The site is a great resource.

- Blair Maclennan
iExec
Marketing and Communications
bm@iex.ec

**Comment by JosefJ** [comment]
It certainly is. For further updates please make a concrete change using the event template - as you know better than me, what you want to change and it will save me time. :) Thanks! 
https://github.com/JosefJ/PragueBlockchainWeek/commit/15f70db44398cf5da4fa7320b06bcecfd96eed2c
