### ISSUE TITLE
#DeFi Summit - Prague

### ISSUE THREAD

**Issue by Cambrial** [JosefJ/PragueBlockchainWeek#9]
If you're submitting an event, please read the instructions below and fill in
the content. Otherwise just remove all the content of this issue and explain
in detail the problem you're experiencing.

---
####################
####################
# This file is a template to create new events.
# _Don't_ remove any text before the colons at the beginning of each line,
# only edit what is after the colon. Example:
# Don't remove the word nor colon on 'description:'
#
# Every line starting with a hash symbol (#) is a comment. It will be ignored
# and can be safely removed, including these instructions.
###############

###########
###########
# The title of the page, displayed by the browser on the title of the window.
# Ideally this is the same as the name of the event.
title: #DeFi Summit - Prague

# Description for this event. This will be rendered as a <meta> tag in the HTML,
# and displayed on the /events page. Keep it short.
# Linebreaks are ignored, but they _must_ start with two spaces.
description: Day-long conference on the latest and most pressing issues in decentralized finance. The event will mix talks on the main stage with participatory breakout sessions and technical workshops led by key actors of the space such as Dharma, Set Protocol and MakerDAO.

#####################
#####################
# The name of the event you're creating.
# Ideally this is the same as the title.
name: #DeFi Summit - Prague

# There _needs_ to be one hyphen before each paragraph.
# Linebreaks are ignored, but they _must_ start with two spaces.
# Indentation is crucial:
# Two spaces before the hyphen, four spaces before the text. _No_ tabs allowed.
# Add or remove paragraphs as needed, but remember the hyphen before each entry.
synopsis:
  -
  -
    _**The event has a limited capacity, please apply using the ticket link below. We will favor individuals who are relevant and can contribute to the discussions that will be held. This event will be filmed and live streamed. Program and schedule will be announced soon**_
  -
    The pace of progress in decentralized finance over the last year has been astounding. Globally-accessible, decentralized financial services went from thought experiments to real products you can use today, most currently with projects like Maker, Dharma and 0x. Still not convinced?
  -
    * In the past 30 days, Loanscan has tracked 1618 loans issued on the Ethereum blockchain — that's 1618 people who were able to tap into a line of uncensorable digital credit from literally anywhere in the world.
    * Back in May 2017, stablecoins were a theoretical construct hardly seen in the wild. There are now not only live stablecoins, but a rapidly growing diversity of them (70!)— and they're working!
    * There are over 1.2 million NFTs listed on OpenSea — this asset class, mind you, hardly **EXISTED** before December of 2017.
  -
    **Things are moving fast if you know where to look.**
  -
    ***
  -
    The #DeFi - Prague summit will be a day-long conference on the latest and most pressing issues in the decentralized finance. A chance to get together for a day as a movement, united by the same overarching vision, to look back on the past year and look forward on what's to come. The event will mix talks on the main stage with participatory breakout sessions and technical workshops led by key actors of the space.
  -
    Shared values of collaboration and openness are reasons why innovation is happening at such an astounding pace in decentralized finance. The DeFi movement upholds these values by bringing together individuals working on decentralized finance to discuss, collaborate and help each other. After our latest #DeFi Summit in San Francisco, we are looking forward to hosting you at our #DeFi Prague Summit on the 29th of October!
  -
    ![Image of event](https://i.imgur.com/WC8Crxi.png)

# The date should be in the format year-month-day (ISO 8601).
# Example: 2018-02-28
date: 2018-10-29
# The date when the event ends. Can be left empty or set to the same day the
# event starts.
endDate: 2018-10-29

# Set the time in 24 hours format, surrounded by quotes.
# _Only_ the starting time!
# Example: '18:00'
time: '09:00'
# Time when the event ends. Can be left empty.
endTime: '17:00'

# The URL where to akquire the tickets. Can be left empty.
tickets: https://airtable.com/shruNBG6DYRGvQQ9l

# If the entrance is free, set zero (0) as the price, or leave it empty.
# _Don't_ write the currency symbol (EUR symbol will be used).
price:

# The name of the venue where the event will be held. Can be left empty.
venue: MeetFactory

# The address to link to a Google map. Please test the address on Google Maps.
# Example: 5. května 1640/65, 140 21 Praha 4
address: Ke Sklárně 3213/15, 150 00 Praha 5, Czechia

# The category of the event. Valid options:
# - conference
# - event
# - hackathon
# - workshop
# - party
# Use _only_ one, and don't capitalize.
category: conference

### DON'T MAKE CHANGES BELOW THIS LINE! ###
---

<Event-Content/>

**Comment by JosefJ** [comment]
Hi, thanks for submitting! 
https://github.com/JosefJ/PragueBlockchainWeek/commit/873da2f34a9164309cd4c6dec17e44d44ca65fe0

Unfortunately, the markup isn't reflected.

**Comment by Cambrial** [comment]
Ho nooo, so there's no way to have bullet points and horizontal lines between text in the event description?

**Comment by Cambrial** [comment]
Reading the description there's a whole part that's been deleted and also stuff that I can edit to try to have formatting without markdown. How can I edit what was posted?
